#! /usr/bin/env python3
from hyper import HTTPConnection
from dnslib import DNSRecord
from base64 import urlsafe_b64encode
from urllib.parse import urlencode


DOH_HOST = "dns.google.com"
DOH_PORT = 443
DOH_PATH = "/experimental?"

HEADERS = {
    "accept": "application/dns-udpwirefomat"
}


dns_query = DNSRecord.question("google.com", "ANY")
enc_query = urlsafe_b64encode(dns_query.pack())

params = urlencode({
    "ct": "",
    "dns": enc_query
})


with HTTPConnection(DOH_HOST, DOH_PORT) as conn:
    s = conn.request("GET", DOH_PATH + params, headers=HEADERS)
    resp = conn.get_response()

    print("Status:", resp.status)
    print("Header:")
    for header, value in resp.headers:
        print("    {}: {}".format(str(header, "ascii"), str(value, "ascii")))

    packet = resp.read()
    rec = DNSRecord.parse(packet)

    print()
    print(rec)

